CREATE TABLE brand (
brandId INTEGER PRIMARY KEY NOT NULL,
brandName text NOT NULL,
brandSegment text,
brandMinSqFt INTEGER,
brandChain text NOT NULL
);

INSERT INTO brand (brandId, brandName, brandSegment, branMinSqFt, brandChain)
VALUES
(001,'Sofitel','Luxury',350,'Accor'),
(002,'Thalassa','Luxury',235,'Accor'),
(003,'Banyan Tree','Luxury',517,'Banyan Tree Holdings'),
(004,'Quorvus Collection','Luxury',NULL,'Carlson Rezidor Hotel Group'),
(005,'Dusit Thani','Luxury',320,'Dusit Thani Group'),
(006,'Conrad','Luxury',235,'Hilton Worldwide'),
(007,'Waldorf Astoria Hotels & Resorts','Luxury',349,'Hilton Worldwide'),
(008,'Curio','Luxury',349,'Hilton Worldwide'),
(009,'The Peninsula Hotels','Luxury',370,'Hongkong and Shanghai Hotels'),
(010,'Grand Hyatt','Luxury',280,'Hyatt Hotels Corporation'),
(011,'Park Hyatt','Luxury',350,'Hyatt Hotels Corporation'),
(012,'InterContinental','Luxury',305,'InterContinental Hotels Group (IHG)'),
(013,'Kempinski','Luxury',356,'Kempinski'),
(014,'Mandarin Oriental','Luxury',363,'Mandarin Oriental Hotel Group'),
(015,'BVLGARI','Luxury',351,'Marriott International'),
(016,'JW Marriott','Luxury',363,'Marriott International'),
(017,'Ritz-Carlton','Luxury',364,'Marriott International'),
(018,'Edition','Luxury',329,'Marriott International'),
(019,'Autograph Collection','Luxury',357,'Marriott International'),
(020,'Anantara Hotels','Luxury',396,'Minor Hotel Group'),
(021,' Resorts & Spas','Luxury',309,'Minor Hotel Group'),
(022,'PER AQUUM Hotels & Resorts','Luxury',359,'Minor Hotel Group'),
(023,'Oberoi','Luxury',367,'Oberoi Hotels & Resorts'),
(024,'JAL City','Luxury',359,'Okura Hotels'),
(025,'Okura','Luxury',396,'Okura Hotels'),
(026,'Regent Hotels & Resorts','Luxury',302,'Regent Hotels & Resorts'),
(027,'Shangri-La Hotels','Luxury',321,'Shangri-La Hotels and Resorts'),
(028,'St. Regis','Luxury',300,'Starwood Hotels and Resorts Worldwide'),
(029,'Luxury Collection','Luxury',339,'Starwood Hotels and Resorts Worldwide'),
(030,'W Hotels','Luxury',395,'Starwood Hotels and Resorts Worldwide'),
(031,'Taj','Luxury',359,'Taj Hotels Resorts and Palaces'),
(032,'Pullman','Upper Upscale',356,'Accor'),
(033,'MGallery','Upper Upscale',396,'Accor'),
(034,'Mama Shelter','Upper Upscale',355,'Accor'),
(035,'Angsana','Upper Upscale',378,'Banyan Tree Holdings'),
(036,'Radisson Blu','Upper Upscale',405,'Carlson Rezidor Hotel Group'),
(037,'Dusit Devarana','Upper Upscale',402,'Dusit Thani Group'),
(038,'Dusit Residence','Upper Upscale',374,'Dusit Thani Group'),
(039,'Fairmont','Upper Upscale',386,'Fairmont Raffles Hotels and Resorts'),
(040,'Raffles','Upper Upscale',388,'Fairmont Raffles Hotels and Resorts'),
(041,'Four Seasons','Upper Upscale',364,'Four Seasons Hotels and Resorts'),
(042,'Hilton','Upper Upscale',376,'Hilton Worldwide'),
(043,'DoubleTree','Upper Upscale',369,'Hilton Worldwide'),
(044,'Andaz','Upper Upscale',367,'Hyatt Hotels Corporation'),
(045,'Hyatt Regency','Upper Upscale',378,'Hyatt Hotels Corporation'),
(046,'Kimpton Hotels & Restaurants','Upper Upscale',371,'InterContinental Hotels Group (IHG)'),
(047,'Crowne Plaza','Upper Upscale',370,'InterContinental Hotels Group (IHG)'),
(048,'Loews Hotels','Upper Upscale',389,'Loews Hotels'),
(049,'Gaylord','Upper Upscale',416,'Marriott International'),
(050,'Marriott','Upper Upscale',351,'Marriott International'),
(051,'Renaissance','Upper Upscale',367,'Marriott International'),
(052,'AC by Marriott','Upper Upscale',365,'Marriott International'),
(053,'Grand Millenium Hotels','Upper Upscale',375,'Millennium Hotels'),
(054,'Oaks Hotels & Resort','Upper Upscale',361,'Minor Hotel Group'),
(055,'Nikko Hotels','Upper Upscale',400,'Okura Hotels'),
(056,'Omni Hotels & Resorts','Upper Upscale',355,'Omni Hotels & Resorts'),
(057,'Westin','Upper Upscale',367,'Starwood Hotels and Resorts Worldwide'),
(058,'Le Meridien','Upper Upscale',350,'Starwood Hotels and Resorts Worldwide'),
(059,'Sheraton','Upper Upscale',369,'Starwood Hotels and Resorts Worldwide'),
(060,'Vivanta By Taj','Upper Upscale',378,'Taj Hotels Resorts and Palaces'),
(061,'Dolce Hotels and Resorts','Upper Upscale',362,'Wyndham Worldwide'),
(062,'Wyndham Grand Hotels and Resorts','Upper Upscale',398,'Wyndham Worldwide'),
(063,'Oakwood','Upper Upscale',414,'Oakwood Corporate Housing'),
(064,'Grand Mercure','Upscale',344,'Accor'),
(065,'The Sebel','Upscale',357,'Accor'),
(066,'Quay West','Upscale',332,'Accor'),
(067,'Park Plaza','Upscale',369,'Carlson Rezidor Hotel Group'),
(068,'Radisson','Upscale',331,'Carlson Rezidor Hotel Group'),
(069,'Radisson Red','Upscale',329,'Carlson Rezidor Hotel Group'),
(070,'Ascend Collection','Upscale',330,'Choice Hotels'),
(071,'Cambria Suites','Upscale',346,'Choice Hotels'),
(072,'Clarion Hotel','Upscale',321,'Choice Hotels'),
(073,'Drury Plaza Hotel','Upscale',348,'Drury Hotels'),
(074,'Dusit Princess','Upscale',354,'Dusit Thani Group'),
(075,'Royal Princess','Upscale',360,'Dusit Thani Group'),
(076,'Swisstel','Upscale',366,'Fairmont Raffles Hotels and Resorts'),
(077,'Embassy Suites','Upscale',333,'Hilton Worldwide'),
(078,'Hilton Garden Inn','Upscale',348,'Hilton Worldwide'),
(079,'Homewood Suites','Upscale',321,'Hilton Worldwide'),
(080,'Home 2 Suites','Upscale',342,'Hilton Worldwide'),
(081,'Hyatt','Upscale',327,'Hyatt Hotels Corporation'),
(082,'Hotel Indigo','Upscale',340,'InterContinental Hotels Group (IHG)'),
(083,'Marriott Executive Apartment','Upscale',348,'Marriott International'),
(084,'Delta Hotels and Resorts','Upscale',352,'Marriott International'),
(085,'Protea Hotels','Upscale',345,'Marriott International'),
(086,'Millennium Hotels','Upscale',349,'Millennium Hotels'),
(087,'Grand Copthrone Hotels','Upscale',340,'Millennium Hotels'),
(088,'AVANI Hotels & Resorts','Upscale',334,'Minor Hotel Group'),
(089,'Trident','Upscale',330,'Oberoi Hotels & Resorts'),
(090,'Traders Hotels','Upscale',328,'Shangri-La Hotels and Resorts'),
(091,' Jen Hotels','Upscale',333,'Shangri-La Hotels and Resorts'),
(092,'Aloft','Upscale',362,'Starwood Hotels and Resorts Worldwide'),
(093,'The Gateway Hotels & Resorts','Upscale',339,'Taj Hotels Resorts and Palaces'),
(094,'Ascott The Residence','Upscale',340,'The Ascott Limited'),
(095,'Wyndham Hotels & Resorts','Upscale',365,'Wyndham Worldwide'),
(096,'Novotel','Upper Midscale',326,'Accor'),
(097,'Suite Novotel','Upper Midscale',374,'Accor'),
(098,'Adagio','Upper Midscale',359,'Accor'),
(099,'Citigate','Upper Midscale',374,'Accor'),
(100,'Best Western Premier','Upper Midscale',334,'Best Western Hotels'),
(101,'Country Inn & Suites','Upper Midscale',332,'Carlson Rezidor Hotel Group'),
(102,'Park Inn','Upper Midscale',357,'Carlson Rezidor Hotel Group'),
(103,'Clarion Inn','Upper Midscale',334,'Choice Hotels'),
(104,'Comfort Inn','Upper Midscale',377,'Choice Hotels'),
(105,'Comfort Suites','Upper Midscale',351,'Choice Hotels'),
(106,'Drury Suites','Upper Midscale',322,'Drury Hotels'),
(107,'Dusit D2','Upper Midscale',338,'Dusit Thani Group'),
(108,'Hampton Inn','Upper Midscale',349,'Hilton Worldwide'),
(109,'Hampton Inn & Suites','Upper Midscale',353,'Hilton Worldwide'),
(110,'Yitel','Upper Midscale',338,'Home Inns'),
(111,'Hyatt House','Upper Midscale',333,'Hyatt Hotels Corporation'),
(112,'Hyatt Place','Upper Midscale',354,'Hyatt Hotels Corporation'),
(113,'Even Hotels','Upper Midscale',313,'InterContinental Hotels Group (IHG)'),
(114,'Staybridge Suites','Upper Midscale',365,'InterContinental Hotels Group (IHG)'),
(115,'Holiday Inn','Upper Midscale',348,'InterContinental Hotels Group (IHG)'),
(116,'Courtyard by Marriott','Upper Midscale',347,'Marriott International'),
(117,'Springhill Suites','Upper Midscale',315,'Marriott International'),
(118,'Residence Inn by Marriott','Upper Midscale',312,'Marriott International'),
(119,'Moxy','Upper Midscale',318,'Marriott International'),
(120,'Copthorne Hotels','Upper Midscale',355,'Millennium Hotels'),
(121,'M Hotels','Upper Midscale',365,'Millennium Hotels'),
(122,'Premier Inn','Upper Midscale',302,'Premier Inn'),
(123,'Kerry Hotels','Upper Midscale',354,'Shangri-La Hotels and Resorts'),
(124,'element by Westin','Upper Midscale',329,'Starwood Hotels and Resorts Worldwide'),
(125,'Four Points','Upper Midscale',362,'Starwood Hotels and Resorts Worldwide'),
(126,'Citadines Apart''Hotel','Upper Midscale',367,'The Ascott Limited'),
(127,'Somerset Serviced Residence','Upper Midscale',371,'The Ascott Limited'),
(128,'TRYP by Wyndham','Upper Midscale',376,'Wyndham Worldwide'),
(129,'Wyndham Garden Hotels','Upper Midscale',310,'Wyndham Worldwide'),
(130,'Mercure','Midscale',342,'Accor'),
(131,'ibis','Midscale',318,'Accor'),
(132,'ibis Styles','Midscale',283,'Accor'),
(133,'Best Western Plus','Midscale',343,'Best Western Hotels'),
(134,'Mainstay Suites','Midscale',348,'Choice Hotels'),
(135,'Quality Inn','Midscale',350,'Choice Hotels'),
(136,'Sleep Inn','Midscale',349,'Choice Hotels'),
(137,'Drury Inn','Midscale',332,'Drury Hotels'),
(138,'Drury Inn and Suites','Midscale',334,'Drury Hotels'),
(139,'Homeinn Plus','Midscale',316,'Home Inns'),
(140,'Holiday Inn Express','Midscale',300,'InterContinental Hotels Group (IHG)'),
(141,'Fairfield Inn','Midscale',349,'Marriott International'),
(142,'TownePlace Suites','Midscale',328,'Marriott International'),
(143,'Kingsgate Hotels','Midscale',312,'Millennium Hotels'),
(144,'Shilo Inns','Midscale',297,'Shilo Inns'),
(145,'Lexington by Vantage','Midscale',349,'Vantage Hospitality'),
(146,'Baymont Inn','Midscale',335,'Wyndham Worldwide'),
(147,'Hawthorn Suites','Midscale',350,'Wyndham Worldwide'),
(148,'Howard Johnson','Midscale',306,'Wyndham Worldwide'),
(149,'Ramada','Midscale',280,'Wyndham Worldwide'),
(150,'Wingate By Wyndham','Midscale',283,'Wyndham Worldwide'),
(151,'Homestead Studio Suites','Midscale',295,'Extended Stay America'),
(152,'ibis Budget','Economy',292,'Accor'),
(153,'hotelF1','Economy',282,'Accor'),
(154,'Americinn','Economy',285,'AmericInn'),
(155,'Best Western','Economy',280,'Best Western Hotels'),
(156,'Econo Lodge','Economy',296,'Choice Hotels'),
(157,'Rodeway Inn','Economy',289,'Choice Hotels'),
(158,'Suburban Extended Stay Hotel','Economy',259,'Choice Hotels'),
(159,'Pear Tree Inn','Economy',276,'Drury Hotels'),
(160,'Home Inns','Economy',256,'Home Inns'),
(161,'Motel 168','Economy',252,'Home Inns'),
(162,'Fairyland Hotels','Economy',292,'Home Inns'),
(163,'Candlewood Suites','Economy',254,'InterContinental Hotels Group (IHG)'),
(164,'InTown Suites','Economy',295,'InTown Suites'),
(165,'Jinjiang Inns','Economy',264,'Jinjiang International'),
(166,'La Quinta Inn','Economy',286,'La Quinta Inns & Suites'),
(167,'Motel 6','Economy',287,'Motel 6'),
(168,'Studio 6','Economy',277,'Motel 6'),
(169,'Ginger Hotels','Economy',275,'Taj Hotels Resorts and Palaces'),
(170,'Americas Best Value Inn','Economy',296,'Vantage Hospitality'),
(171,'Canadas Best Value Inn','Economy',257,'Vantage Hospitality'),
(172,'Days Inn','Economy',294,'Wyndham Worldwide'),
(173,'Howard Johnson Express Inn','Economy',299,'Wyndham Worldwide'),
(174,'Knights Inn','Economy',267,'Wyndham Worldwide'),
(175,'Microtel Inn','Economy',286,'Wyndham Worldwide'),
(176,'Super 8','Economy',280,'Wyndham Worldwide'),
(177,'Travelodge','Economy',293,'Wyndham Worldwide'),
(178,'Extended Stay America','Economy',274,'Extended Stay America'),
(179,'Red Roof Inn','Economy',293,'Red Roof Inn');